# Generated by Django 4.0.3 on 2022-04-02 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedapp', '0005_alter_post_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_hide_post', 'Can hide post')]},
        ),
    ]
